apiVersion: v1
kind: Service
metadata:
  name: "traefik-dev"
  labels:
    app: traefik
    chart: traefik-dev-1.0.0
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  # use this if you want to inline in --set externalIps={a,b,c}
  externalIPs: {{ .Values.externalIps }}
  selector:
    app: traefik
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https