name: Build MyIaC

on:
  push:
    branches: [issue/*, feature/*, update/*, fix/*, master]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v cmd/myiac/myiac.go

      - name: Test cli
        run: ./myiac --help | grep "Infrastructure as code"

      - name: GO test
        run: go test ./...  -coverprofile=coverage.txt

      - name: Code Coverage Upload
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
